FROM --platform=arm64 rust:latest

RUN apt update -y
RUN apt-get install libasound2-dev libxi-dev libxtst-dev -y

RUN rustup target add aarch64-unknown-linux-gnu
RUN rustup toolchain install stable-aarch64-unknown-linux-gnu

WORKDIR /app

CMD [ "cargo", "build", "-r", "--target", "aarch64-unknown-linux-gnu" ]