FROM --platform=amd64 rust:latest

RUN apt update -y
RUN apt-get install libasound2-dev libxi-dev libxtst-dev protobuf-compiler -y

RUN rustup target add x86_64-unknown-linux-gnu
RUN rustup toolchain install stable-x86_64-unknown-linux-gnu

WORKDIR /app

CMD [ "cargo", "build", "-r", "--target", "x86_64-unknown-linux-gnu" ]
